#### matrix in python 

In [1]:
def sumint():
    a=int(input("enter the  no:-" ))
    b=int(input("enter the  no:-" ))
    "sum of two no"
    sum=a+b
    print("sum = " , sum)
    return
def diffint():
    a=int(input("enter the  no:-" ))
    b=int(input("enter the  no:-" ))
    "sum of two no"
    dif=a-b
    print("sum = " , dif)
    return
sumint()
diffint()

enter the  no:- 1
enter the  no:- 1


sum =  2


enter the  no:- 1
enter the  no:- 1


sum =  0


In [2]:
def fibo(n):
    a,b=0,1
    n=int(input("enter the  no:-" ))
    for i in range(n):
        print(a)
        a,b = b,a+b
fibo(10)

enter the  no:- 2


0
1


In [3]:
def dic1(n):
    m=int(input("enter the  no:- "))
    b={}
    flag=1
    while  flag<=m:
        
        b[flag]=flag*flag
        flag+=1
    print(b)
dic1(10)

enter the  no:-  3


{1: 1, 2: 4, 3: 9}


In [4]:
import random 
def randomlist():
    outer_list = []
    for i in  range(3):
        inner_list = []
        for i in range(3):
            inner_list.append(random.randint(1 , 100))
        outer_list.append(inner_list)
    return outer_list

In [5]:
def printlist(a):
    for i in range(len(a)):
        for j in range(len(a[i])):
            print(a[i][j] , end="  ")
        print()

In [6]:
def addlist(l1 , l2):
    l = []
    for i in range(len(l1)):
        innerlist= []
        for j in range( len(l1[i]) ):
            innerlist.append(l1[i][j] + l2[i][j])
        l.append(innerlist)
    return l

In [7]:
l1 = randomlist()


In [8]:
l2 = randomlist()


In [9]:
l = addlist(l1 , l2)



In [10]:
printlist(l1)
print()
printlist(l2)
print()
printlist(l)
print()

42  80  76  
15  36  49  
97  95  11  

38  88  74  
98  68  8  
22  61  1  

80  168  150  
113  104  57  
119  156  12  



In [11]:
import numpy as np


In [12]:
a = np.array([[1 , 2, 3] , [ 4, 5 , 6 ] , [ 7 ,8 , 9 ] ] )
b = np.array([[1 , 2, 3] , [ 4, 5 , 6 ] , [ 7 ,8 , 9 ] ] )
c = a + b
d = a - b 
e = a * b
f = a / b 
g = a + 1 


In [13]:
c


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [14]:
d


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [15]:
e

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [16]:
f

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
g

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [18]:
a.dot(b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
a.dot(b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [22]:
np.min(a , axis=1)

array([1, 4, 7])

In [23]:
l1 = randomlist()


In [24]:
print(l1)

[[81, 20, 98, 71], [55, 18, 77, 63], [60, 80, 25, 86], [17, 43, 68, 3]]


In [8]:
l =[[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
   ]

In [2]:
l1 = randomlist()

In [3]:
l2 = randomlist()

In [6]:
print(l1)

[[16, 32, 93], [56, 97, 13], [8, 96, 53]]


In [7]:
print(l2)

[[34, 81, 89], [95, 41, 43], [97, 79, 14]]


In [11]:
l = addlist(l1, l2)
print(l)

[[50, 113, 182], [151, 138, 56], [105, 175, 67]]


In [12]:
print(l)

[[50, 113, 182], [151, 138, 56], [105, 175, 67]]


In [12]:
import numpy as np 


In [15]:
a = np.array([[1 , 2, 3 ] , [4 , 5 ,6 ] , [7 , 8 ,9]])

In [16]:
b = np.array([[1 , 2, 3] , [ 4, 5 , 6 ] , [ 7 ,8 , 9 ] ] )

In [34]:
c = np.min(a , axis= 0) 

In [35]:
print(c)

[1 2 3]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
c = [9 , 9, 9 ,9]
ans = []
i = len(c) -1 
ans.append((c[i]+1)%10)
carry = (c[i]+1)//10
print(carry)
i-=1
while(i >=0):
    print(i , end="  " )
    d =(c[i] + carry)%10
    carry =(c[i] + carry) //10
    ans.append(d)
    i-=1
if(carry==1):
    ans.append(1)
ans.reverse()
print()
print(ans)

1
2  1  0  
[1, 0, 0, 0, 0]


In [ ]:
[1 , 2, ,3 ,4 , 6 , -1 , -2 , - 3 , 1 ,2 , 0 ]   0 

- h.w
- https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/